name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - pre_prod
      - prod

jobs:
  main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Running main pipeline"

  pre_prod:
    if: github.ref == 'refs/heads/pre_prod'
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Running pre_prod pipeline"

  prod:
    if: github.ref == 'refs/heads/prod' && success()
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Running prod pipeline"
