name: Branch Specific Actions

on: 
  push:
    branches:
      - main
      - pre_prod
      - prod

jobs:

  main:
    name: main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo branch name for main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "This job was run on the main branch"

  pre_prod:
    name: pre_prod
    runs-on: ubuntu-latest
  
    steps:
      - name: Echo branch name for pre_prod
        if: ${{ github.ref == 'refs/heads/pre_prod' }}
        run: echo "This job was run on the pre_prod branch"

  prod:
    name: prod
    runs-on: ubuntu-latest

    steps:
      - name: Echo branch name for prod
        if: ${{ github.ref == 'refs/heads/prod' }}
        run: echo "This job was run on the prod branch"
